# Generated by Django 4.2.25 on 2025-12-27 12:10

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('date', models.DateTimeField(db_index=True)),
                ('text', models.TextField(db_index=True)),
                ('views', models.IntegerField(default=0)),
                ('forwards', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('has_media', models.BooleanField(default=False)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('video_data', models.JSONField(blank=True, null=True)),
                ('when_added', models.DateTimeField(auto_now_add=True)),
                ('when_updated', models.DateTimeField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.channel')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('channel', 'telegram_id')},
            },
        ),
    ]
